---
- name: add grafana repo
  become: yes
  become_method: sudo
  yum_repository:
    name: grafana
    description: Kibana repository for 7.x packages
    baseurl: https://packages.grafana.com/oss/rpm
    gpgcheck: no
    enabled: yes

- name: install grafana
  become: yes
  become_method: sudo
  dnf:
    name: grafana
    state: latest

- name: enable grafana service
  become: yes
  become_method: sudo
  service:
    name: grafana-server
    enabled: yes

- name: start grafana service
  become: yes
  become_method: sudo
  service:
    name: grafana-server
    state: started

- name: reset grafana admin password
  become: yes
  become_method: sudo
  shell: grafana-cli admin reset-admin-password admin@2021

# grafana-cli plugins install grafana-piechart-panel

# https://github.com/grafana/grafana/issues/1789
- name: check that a grafana api returns a status 200
  uri:
    url: http://10.0.0.173:3000/api/datasources/name/Elasticsearch
    user: admin
    password: admin@2021
    force_basic_auth: yes
  register: grafana_elasticsearch
  failed_when: false
  changed_when: false

- name: enable elasticsearch datasource
  uri:
    url: http://10.0.0.173:3000/api/datasources
    method: POST
    user: admin
    password: admin@2021
    body:
      name: "elasticsearch"
      type: "elasticsearch"
      url: "http://10.0.0.172:9200"
      access: "proxy"
      isDefault: true
    force_basic_auth: yes
    status_code: 200
    body_format: json
  when: grafana_elasticsearch.status == 404