---
- name: update cache & full system update
  become: yes
  become_method: sudo
  apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600
    force_apt_get: true

- name: install apache2
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
    name: apache2
    state: latest

- name: restart apache2
  become: yes
  become_method: sudo
  service:
    name: apache2
    state: restarted